name: "Hetzner DynDNS"
description: "Wrapper for 'Docker Hetzner DDNS' from https://github.com/mRy0/HetznerApiDynDNS/"
url: "https://github.com/DieserDave/hassio-addons/"
version: "2.0.0"
slug: "hetzner_ddns"
init: false
boot: auto
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  APIKEY: ""
  ZONENAME: "world.org"
  ARECORDNAMES__0: "my"
schema:
  APIKEY: str
  ZONENAME: str
  ARECORDNAMES__0: str?
  
