name: "Nextcloud"
description: "Nextcloud for Home Assistant"
url: "https://github.com/DieserDave/hassio-addons/"
version: "28.0.2"
slug: "nextcloud"
init: false
boot: auto
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - share:rw
ports:
  80/tcp: null
ports_description:
  80/tcp: "Web interface"
webui: "http://[HOST]:[PORT:80]"
panel_icon": "mdi:cloud-sync"
options:
  NEXTCLOUD_TRUSTED_DOMAINS: ""
  overwrite_cli_url: ""
  overwriteprotocol: ""
schema:
  NEXTCLOUD_TRUSTED_DOMAINS: "str?"
  overwrite_cli_url: str?
  overwriteprotocol: str?
